#!/bin/bash

rmdir -rf /Applications/PlexConnect
mkdir /Applications/onlytemp
cd /Applications/onlytemp
git clone git://github.com/wahlmanj/PlexConnect.git
cd /Applications
git clone git://github.com/iBaa/PlexConnect.git
cd /Applications/PlexConnect/support
mkdir IOS_jailbreak
cp -R /Applications/onlytemp/PlexConnect/support/IOS_jailbreak/* /Applications/PlexConnect/support/IOS_jailbreak
cd /Applications/PlexConnect/support/IOS_jailbreak
cp update.bash /private/var/stash/bin
chmod +x install.bash
./createcert.bash
./install.bash
./restart.bash
rm -R /Applications/onlytemp
exit 0
