#!/bin/bash

rmdir -rf /Applications/PlexConnect
cd /Applications
git clone git://github.com/iBaa/PlexConnect.git
tar -xvf PlexConnect.tar.gz -C /Applications
cd /Applications/PlexConnect/support/IOS_jailbreak
chmod +x install.bash
./createcert.bash
./install.bash
./restart.bash
cd /Applications
rm PlexConnect.tar.gz
exit 0
